name: webapp 
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - blinker==1.9.0
  - click==8.1.8
  - colorama==0.4.6
  - dnspython==2.7.0
  - email_validator==2.2.0
  - flask==3.1.0
  - greenlet==3.1.1
  - idna==3.10
  - itsdangerous==2.2.0
  - jinja2==3.1.5
  - markupsafe==3.0.2
  - mysqlclient==2.2.7
  - numpy==2.2.2
  - typing_extensions==4.12.2
  - werkzeug==3.1.3
  - pip
  - pip:
      - Bootstrap-Flask==2.4.1
      - Flask-MySQLdb==2.0.0
      - Flask-WTF==1.2.2
      - WTForms==3.2.1
      - dominate==2.9.1
      - visitor==0.1.3
